##before run the code, please load the library at console command
##> library(xml2)> library(rvest)> library(stringr)

url <- 'https://www.amazon.in/OnePlus-Mirror-Black-64GB-Memory/dp/B0756Z43QS?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=aee9a916-6acd-4409-92ca-3bdbeb549f80'
webpage <- read_html(url)
title_html <- html_nodes(webpage,'h1#title')
title <- html_text(title_html)
title <- str_replace_all(title, "[\r\n]" , "")
head(title)
price_html <- html_nodes(webpage, 'span#priceblock_ourprice')
price <- html_text(price_html)
str_replace_all(price, "[\r\n]" , "")
head(price)
desc_html <- html_nodes(webpage, 'div#productDescription')
desc <- html_text(desc_html)
desc <- str_replace_all(desc, "[\r\n\t]" , "")
desc <- str_trim(desc)
head(desc)
rate_html <- html_nodes(webpage, 'span#acrPopover')
rate <- html_text(rate_html)
rate <- str_replace_all(rate, "[\r\n]" , "")
rate <- str_trim(rate)
head(rate)
size_html <- html_nodes(webpage, 'div#variation_size_name')
size_html <- html_nodes(size_html, 'span.selection')
size <- html_text(size_html)
size <- str_trim(size)
head(size)
color_html <- html_nodes(webpage, 'div#variation_color_name')
color_html <- html_nodes(color_html, 'span.selection')
color <- html_text(color_html)
color <- str_trim(color)
head(color)
product_data <- data.frame(Title = title, Price = price,Description = desc, Rating = rate, Size = size, Color = color)
str(product_data)

##before run JSON format, please load the library at console command
##>library(jsonlite)

json_data <- toJSON(product_data)
cat(json_data)
